// Listado completo de razas por especie
export const BREEDS_BY_SPECIES: Record<string, string[]> = {
  Perro: [
    "Affenpinscher",
    "Afgano (Lebrel Afgano)",
    "Airedale Terrier",
    "Akita Inu",
    "Akita Americano",
    "Alaskan Malamute",
    "American Bully",
    "American Staffordshire Terrier",
    "Antiguo Perro Pastor Inglés (Bobtail)",
    "Azawakh (Galgo Africano)",
    "Barbet",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Bedlington Terrier",
    "Bichón Frisé",
    "Bichón Habanero",
    "Bloodhound (Perro de San Huberto)",
    "Border Collie",
    "Border Terrier",
    "Bóxer",
    "Boyero de Berna (Bernés de la Montaña)",
    "Braco Alemán de Pelo Corto",
    "Bulldog Francés",
    "Bulldog Inglés",
    "Bull Terrier",
    "Cairn Terrier",
    "Cane Corso",
    "Caniche (Poodle) - Gigante, Mediano, Enano, Toy",
    "Carlino (Pug)",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chow Chow",
    "Cocker Spaniel Americano",
    "Cocker Spaniel Inglés",
    "Collie (Smooth y Rough)",
    "Corgi Galés Pembroke",
    "Dálmata",
    "Dandie Dinmont Terrier",
    "Deerhound Escocés",
    "Dóberman",
    "Dogo Alemán (Gran Danés)",
    "Dogo Argentino",
    "Dogo de Burdeos",
    "Fox Terrier (Pelo Liso y Pelo Duro)",
    "Galgo Español",
    "Golden Retriever",
    "Gran Boyero Suizo",
    "Gran Basset Grifón Vendeano",
    "Hamiltonstovare",
    "Hovawart",
    "Husky Siberiano",
    "Irish Setter (Setter Irlandés)",
    "Irish Wolfhound (Lobero Irlandés)",
    "Jack Russell Terrier",
    "Kai Ken",
    "Keeshond",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Landseer",
    "Leonberger",
    "Maltés (Bichón Maltés)",
    "Mastín Español",
    "Mastín Tibetano",
    "Mestizo",
    "Miniature Bull Terrier",
    "Newfoundland (Terranova)",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Ovejero Alemán (Pastor Alemán)",
    "Papillón",
    "Pastor Australiano",
    "Pastor Belga (Malinois, Tervueren, Groenendael, Laekenois)",
    "Pastor de Shetland (Sheltie)",
    "Pastor Vasco (Euskal Artzain Txakurra)",
    "Perro de Agua Español",
    "Perro Lobo Checoslovaco",
    "Pinscher Miniatura",
    "Podenco Ibicenco",
    "Pomerania (Spitz Enano)",
    "Ratonero Bodeguero Andaluz",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Sabueso Español",
    "Saluki (Galgo Persa)",
    "Samoyedo",
    "Schnauzer (Miniatura, Mediano, Gigante)",
    "Scottish Terrier",
    "Shiba Inu",
    "Shih Tzu",
    "Soft Coated Wheaten Terrier",
    "Springer Spaniel Inglés",
    "Staffordshire Bull Terrier",
    "Teckel (Dachshund) - Pelo corto, Pelo largo, Pelo duro",
    "Terrier Escocés",
    "Terrier Tibetano",
    "Vizsla",
    "Volpino Italiano",
    "Weimaraner",
    "West Highland White Terrier (Westie)",
    "Whippet",
    "Yorkshire Terrier",
  ],
  Gato: [
    "Abisinio",
    "American Curl",
    "American Shorthair",
    "Angora Turco",
    "Azul Ruso",
    "Bengalí",
    "Birmano",
    "Bosque de Noruega",
    "British Shorthair",
    "Burmés",
    "Chartreux",
    "Común Europeo",
    "Cornish Rex",
    "Devon Rex",
    "Exótico de Pelo Corto",
    "Himalayo",
    "Maine Coon",
    "Manx",
    "Mestizo",
    "Munchkin",
    "Oriental",
    "Persa",
    "Ragdoll",
    "Sagrado de Birmania",
    "Scottish Fold",
    "Siamés",
    "Siberiano",
    "Somalí",
    "Sphynx",
    "Toyger",
    "Turco Van",
  ],
  Conejo: [
    "Angora",
    "Belier",
    "Californiano",
    "Cabeza de León",
    "Chinchilla",
    "Enano Holandés",
    "Gigante de Flandes",
    "Hotot",
    "Mini Lop",
    "Mestizo",
    "Rex",
    "Toy",
  ],
  Ave: [
    "Agapornis",
    "Cacatúa",
    "Canario",
    "Carolinas/Ninfas",
    "Cotorra",
    "Diamante Mandarín",
    "Guacamayo",
    "Jilguero",
    "Loro",
    "Periquito",
  ],
  Roedor: ["Chinchilla", "Cobaya/Conejillo de Indias", "Degú", "Gerbil", "Hámster", "Jerbo", "Ratón"],
  Reptil: ["Camaleón", "Gecko", "Iguana", "Pitón", "Serpiente del Maíz", "Tortuga"],
  Otro: ["Mestizo", "Desconocido"],
}

// Función para obtener razas filtradas por búsqueda
export function getBreedsBySpecies(species: string, query = ""): string[] {
  // Normalizar el nombre de la especie: primera letra mayúscula, resto minúsculas
  const normalizedSpecies = species.charAt(0).toUpperCase() + species.slice(1).toLowerCase()

  console.log("[v0] Looking for breeds of species:", normalizedSpecies)
  const breeds = BREEDS_BY_SPECIES[normalizedSpecies] || []
  console.log("[v0] Found breeds count:", breeds.length)

  if (!query) {
    return breeds
  }

  const normalizedQuery = query.toLowerCase().trim()
  const filtered = breeds.filter((breed) => breed.toLowerCase().includes(normalizedQuery))
  console.log("[v0] Filtered breeds count:", filtered.length)
  return filtered
}
