-- Eliminar todos los datos antiguos y crear datos completamente corregidos
DELETE FROM dog_beaches;

-- Insertar TODAS las playas con títulos corregidos (sin ubicación), imágenes del campo gx_media_links, y todas las URLs
INSERT INTO dog_beaches (name, municipality, province, latitude, longitude, description, image_url, more_info_url, nearby_accommodations_url) VALUES
('Playa de la Rubina', 'Empurivabrava', 'Girona', 42.258182, 3.148249, 'La Playa de La Rubina, en Empuriabrava admite perros en verano a cualquier hora', 'https://lh3.googleusercontent.com/umsh/AN6v0v79Vth60LeX3MYviU8mlcfGdHbiIGFsXpbmRjq7sMO-gHV_iHZIB3E-S8DBJu-yZEFLMNkeQHzMzjtJacTSPbub71faG22T9TCJEqIrBiyBF-MGH5270DmgfbTEO6Y9Lb1yRn38v7DtzkzjzFKal97SgprybCEvoqhXsXXaIQ', 'https://www.playasparaperros.com/la-rubina-playa-perros-empuriabrava-girona/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-la-playa-perros-la-rubina/'),

('Playa La Picòrdia', 'Arenys de Mar', 'Barcelona', 41.577706, 2.551533, 'Habilitada en 2017. Abierta desde el 1 de junio al 16 de septiembre', 'https://mymaps.usercontent.google.com/hostedimage/m/*/3AKcrxGTBlxUuH7qbWFLTShyap0YYSCcJkPmcp7EOT4CwiYsk2F3wQQmM03DZ_mcEsvlgTkomEowRPmo14VMbL7jFVAYz8TrPukORSHL5zgfnIoSg8D6C5avnO-o-ZcH7aIT43WWnqcn0EJu65XpfMZGnpSiAyiUeIocV2y9i4Mi_qKb_5DFnN0gyyl84ZIw7-3NDi7K2nCOBEYZNhw?authuser=0&fife=s16383', 'https://www.playasparaperros.com/la-picordia-playa-perros-arenys-mar-barcelona/', NULL),

('Playa Bon Caponet', 'Ametlla de Mar', 'Tarragona', 40.875484, 0.796675, 'En la Playa de Bon Caponet está permitida la entrada de perros en verano a cualquier hora del día', 'https://lh3.googleusercontent.com/umsh/AN6v0v6JZgVMwcnwvGUsZ82uaqE5v1rZeOizTixC7pHCJGY4B-scpj3XvNU-ogw7O5X-o26Rqg0NZYlBIzTVh7-5hROKDPVK8btxCtJW1E_nBAo0QnkYTbxx8JeHU1ueDjnqh00uUxdw6-Tt-eU0dodJ8vp4nZzgGGUL61xJU-y40GImlZzrGGRdRE2B0c1eiNEqwJKPpwAoCUCDnlpR2J4VDuYlRGwoDlH6-IlvCD_v_yNNnOxHcqhPkFXavxPpLIxq--ZBYs0a7yRWZM1W', 'https://www.playasparaperros.com/bon-caponet-playa-perros-ametla-mar-tarragona/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-cala-bon-caponet/'),

('Playa La Platjola', 'Alcanar', 'Tarragona', 40.532442, 0.517603, 'La Playa La Platjola admite perros en verano a cualquier hora', 'https://lh3.googleusercontent.com/umsh/AN6v0v7id8H7yYrYGoo6oREMt8WeSVjcM7WJs4H13NNbRVEhTZVXnAEsghQ2QDHSPi0rFkV2BGVwjjJ6Y4rGbvNzBUq52PtmvLskV3VtWlb4_3eOJfrXamk_ggEZMtHT7xULHfDwiqwOJhc_Qbkd2cCQgSTh1HPn340', 'https://www.playasparaperros.com/la-platjola-playa-perros-alcanar/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-la-playa-la-platjola/'),

('Cala Cementiri', 'Ametlla de Mar', 'Tarragona', 40.889361, 0.810203, 'A esta pequeña cala se puede acceder con perro en verano a cualquier hora del día', 'https://mymaps.usercontent.google.com/hostedimage/m/*/3AKcrxGQS65kyeG1bYv1BszzCZ3J0pDRbBgHKNeQg0S-54I6_fJ3v5fsGHFNrm0ke6VIvG7lDwBMTwZDgBJ44I3KEGOGmSVCJOGEWSdb-XfbK1kvdBWuirOY8I16yHJv_BmvayBZdbYg2DUZaBfR75FiRIUL7xR0lZ7Or_2hslzCI9sa5KnermRsZc-fTnGExNvH2ZFfdu1s1_Ty7Tw?authuser=0&fife=s16383', 'https://www.playasparaperros.com/cala-cementiri-playa-perros-ametlla-mar/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-cala-cementiri/'),

('Platja de la Bassa de l''Arena', 'Deltebre', 'Tarragona', 40.749684, 0.810878, 'Puedes acceder con perro en verano a cualquier hora del día', 'https://lh3.googleusercontent.com/umsh/AN6v0v4ElQrPqD0ANM6VCpeDZT8uueo7DLoFLG3lLGMDvz_2iDNhTCOON3ttgRVE5T-2t8wRHfXN8MgLFrOGiwkAhsZjvAFKKoWbTHTnw_D5o-Z30ehJSYXo5dB9-Ugu8VEoyX9vXRULfAHsSnxN7L9E_Kg_', 'https://www.playasparaperros.com/bassa-la-arena-playa-perros-deltebre/', 'https://www.playasparaperros.com/apartamentos-admiten-perros-cerca-la-playa-bassa-larena-riumar/'),

('Playa Riera d´Alforja', 'Cambrils', 'Tarragona', 41.063889, 1.054438, 'De reciente inauguración, puedes acceder a cualquier hora en verano.', 'https://mymaps.usercontent.google.com/hostedimage/m/*/3AKcrxGSnjQt0yKAcupL0pLe2BS3CrIv6K0yk9UhUWWjzRYVEu2wPT87MriI5zqdZYuSU0VuFWLendpDhUp6fadACpDBNL-cnjoCLEIHnL8jkDQJSWgKb49yjPxPhVyVjrCdahj3PliBu_-m_w807HEfaD8HPUPrwy0fGAT7nsIu9-0jhW1H-MNTv2zbaE8hi0mRdj9dpBTobq2vfQw?authuser=0&fife=s16383', 'https://www.playasparaperros.com/riera-dalforja-playa-perros-cambrils/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-la-riera-dalforja/'),

('Playa de Aiguaoliva', 'Vinarós', 'Castellón', 40.443056, 0.453691, 'Playa de Piedra donde puedes acceder con tu mascota en verano a cualquier hora', 'https://lh3.googleusercontent.com/umsh/AN6v0v750nNZab3N9LyDgkHEMEXglLjzgKYHJ_tNGWij_w3ci47J3spqQ_GG_TTMf-16hg6gPZfiV2TtA26d4QFNjWSTSCJDEEdjPQvVuESwPaE_DIwXyVST6nmabMdhaozz6LfLiMaKe1F3', 'https://www.playasparaperros.com/playa-aiguaoliva-playa-perros-vinaros/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-la-playa-aiguaoliva/'),

('Playa Punta del Riu', 'Campello', 'Alicante', 38.416556, -0.390690, 'A esta playa para perros de Campello puedes acudir en verano a cualquier hora del día', 'https://lh3.googleusercontent.com/umsh/AN6v0v7ETG1GqE7AmpvXmXpmS4KZdWCOGYO9C7fZFO2aBgyZlhUq0wBuYwWdiHs1_dvAjn2mX2VOBd8u1kTYrvoa_kdNLt9_Jbz06Cj8fVqkRE0mIh-sS-6VVMRf4Sufl9ITIY-wJ62CQA2pY6I3bXVxaoYAKr01BVplzKMcnRggIw0', 'http://www.redcanina.es/playa-para-perros-en-campello/', 'http://www.redcanina.es/hoteles-que-admiten-perros-cerca-de-la-playa-para-perros-de-campello/'),

('Cala del Xarco', 'Villajoyosa', 'Alicante', 38.491024, -0.278987, 'Puedes acceder con tu perro en verano a cualquier hora del día', 'https://lh3.googleusercontent.com/umsh/AN6v0v6hesSwJHVzyBlGmpuAc9vVMqI4Z_389gu_bZPb8hl9QOEKeG5Ka_frLa4LLujPtM1XQ1kuoIj3xWGx2LvIbe3OJkAqMf9FYln4uzVZrXTNdlRzreQCZNgLcZ1e', 'http://www.redcanina.es/playa-para-perros-el-xarco-en-villajoyosa/', 'http://www.redcanina.es/hoteles-y-apartamentos-que-admiten-perros-cerca-de-cala-el-xarco/'),

('Caleta dels Gossets', 'Santa Pola', 'Alicante', 38.214461, -0.507737, 'Disponible todo el año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v6kRmaitzU5YU66N_MDUT4iN3BGR-1A0PpcDNzziWY1blkGi2M6yv5KMdGF066aV7Kkp9lGcdfNjtcPripUwE6DYRD6-nBcZxRvWekylVnlX7CiqKAlekTtKYKewo_k6B5jIXteJ01GCw', 'http://www.redcanina.es/playa-para-perros-en-santa-pola-junto-al-cabo/', 'http://www.redcanina.es/hoteles-y-apartamentos-que-admiten-perros-cerca-de-la-playa-canina-de-santa-pola/'),

('Playa de Agua Amarga', 'Alicante', 'Alicante', 38.303715, -0.518150, 'Disponible todo el año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v6z_5_D1KD4uHDZnREOl1khb1zqIpPTEd_v-d3j6G_-olYjbU7CU1IBAHgIyBEEgwYETqsV4_I9c44EjFdvl98GPPF5PUj5-9bvDpn9gAxFYcK8BDfhUI6AI2b_NYH44UD9mg6X', 'http://www.redcanina.es/playa-para-perros-en-agua-amarga-alicante/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-de-la-playa-de-agua-amarga/'),

('Playa Sierra de las Moreras', 'Mazarrón', 'Murcia', 37.561629, -1.296129, 'Playa semiurbana con suelo de arena gruesa', 'https://lh3.googleusercontent.com/umsh/AN6v0v66L6RulNgJl5wQ-1luQGy0dp09vJPV8OBJy-7joc5Dw_ZJ33SSH2cdxDHWOmigk1dSKwXFxGtkL-6SccEVUrOw-Pw615CS_XvgQWjKAN9kIpi9rUGkXWz064-aknpMo2VFE-gsPElNNjoHXR6UwLM8Z_bkHaFmZRgpeVdrKxvoRW0xEYdfChjrsEwQZKiIZgv3geJg6g', 'http://www.redcanina.es/playa-sierra-de-las-moreras-para-perros-en-mazarron/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-la-playa-sierra-de-las-moreras/'),

('Playa El Gachero', 'Mazarrón', 'Murcia', 37.572805, -1.248686, 'Sin restricciones horarias en verano', 'https://lh3.googleusercontent.com/umsh/AN6v0v7UXrachNEv7dOyncTN_6o9rUju14_V_eVp02RKNn8GsbVoBB0lnmvrb8OdxiUu0e7mLrF_mKO-Ig5kF7Kn6kg3JKpENhjMstXges1MdKlFGAIa-vtqDKRlPnVS8EOmgFrSWuXYvKDegGZvOQKiL_nsLQavclSKWG4cra_ygMYO', 'http://www.redcanina.es/playa-el-gachero-para-perros-en-mazarron/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-de-la-playa-canina-el-gachero/'),

('Playa de Cobaticas', 'Mazarrón', 'Murcia', 37.537933, -1.369621, 'Abierta Todo el Año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v4qoS5rkms0E1sdLA4f7helbNz65QsNZCcLNEVHeNjRo-k2eKuX6WAB_HsaP99R0IrS7GHbm21hKoIow_TifS0vaAJIXe1hxj3FhpV2WXOVikco83F-aYXa4EBeKK4QzmdnJuKK5bNWXsSIo_TwF5suHRiFnkGuPYfRfjxTtcR8HuQBbBXrfd21AhH4gu6PVNm4IAgs1ZOSGn5-7iTlmnRjB_-dk0NsBHZPpN9KLEnXxU-jyoZpzxpTJGuus63fSbvmdGMXmpRCDg', 'http://www.redcanina.es/playa-de-las-cobaticas-para-perros-en-mazarron/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-de-la-playa-para-perros-de-cobaticas-en-murcia/'),

('Cala Vallcarca', 'Sitges', 'Barcelona', 41.239653, 1.862709, 'Abierta todo el año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v7VVvFx4wahVj03m5FqA5hz2e6hXcBGlvP7Qx5WfdaUhrUSPtfnrcNFe2nZlKqw8bNyXlfTDBTJHaV3UzBOtIHkhOZ7256O1rgp81HjKtEKNQy0uk8htno17HJK7GAZ4MFJ4heJgZHz04gRuyiuz1JlYLzS7OcujErVDAftYQ', 'https://www.playasparaperros.com/cala-vallcarca-playa-perros-sitges/', 'https://www.playasparaperros.com/hoteles-admiten-perros-cerca-cala-vallcarca-barcelona/'),

('Playa O Espiño', 'O Grove', 'Pontevedra', 42.458923, -8.919479, 'Abierta Todo el Año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v7_09bMbOGqtX9BOpsMeFHK2CcCk0UOvGtqN5siAcuF_eLyCTfd6O_QqfwRfR5gNq8F_gbaNRjZiboeNe4_jjxaEBzuaAOpsOaiGOUyQnCtUWot', 'https://www.playasparaperros.com/playas-portino-espino-playas-perros-grove-pontevedra/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-grove-cerca-las-playas-perros/'),

('Playa canina de Ares', 'Ares', 'A Coruña', 43.421866, -8.243812, 'Abierta Todo el Año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v6GF8qC078_-db96FgL9ULgibKzDepTCmukuZ6l5ttLEW8ZAGCR-gHKh5YlkS6KPVVKA8z5OuAmwd6BgZG4rqaEB-ZrHXxqpj1ZwJ_yyi_2gdhYa-B1O02rkob2Xr3JirpAbgOasEbrfhjHWF0TC8hZIcD_qKW6Z0fwvlZjJl1cEA_iy6u5XqRY2PRjLRCmd9SH', 'https://www.playasparaperros.com/playa-canina-de-ares-a-coruna/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-la-playa-canina-ares/'),

('Playa de Muelle Oriñon', 'Castro Urdiales', 'Cantabria', 43.394880, -3.320038, 'Los perros pueden pasear sueltos todo el año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v5lgYAuHqslPQHVq5YRJhUDcsb1sZOzW4ScyMsdRthaVChRBFE22u-JEnngpFMtitDjR9-AqXvn-JXai6H11jlTNHwbhuExuaX1U_GZwDPgXuHVS1FstpgdbodvVCjMMHtQVGlSDhGRSVp_xIvNv6sh_Sqd5Q', 'https://www.playasparaperros.com/muelle-orinon-playa-perros-castro-urdiales-cantabria/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-castro-urdiales-cerca-la-playa-canina-muelle-orinon/'),

('Playa Arcisero', 'Castro Urdiales', 'Cantabria', 43.373149, -3.204456, 'Los perros pueden pasear libremente durante todo el año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v5eZ5BY3N84udX1TvvyJNgl8IkhgbQyo07WEEugyDaWq_RYBKrVfNtS5wQYg2CJROg_CnOIre5dwtuQipgKzVCKjRTX-A6ZI_wRukWKR7uJBQvtERAf6xAouvOX8ygjn0kvGACgDtmZxVR9PtruC_FydB0l5C_DvvhvD3sFtNP-mPxnFQ', 'https://www.playasparaperros.com/playa-arcisero-playa-perros-castro-urdiales-cantabria/', 'https://www.playasparaperros.com/alojamientos-admiten-perros-cerca-la-playa-canina-playa-arcisero-castro-urdiales/'),

('Es Carnatge', 'Palma de Mallorca', 'Mallorca', 39.542894, 2.700877, 'Abierta todo el año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v6xK8FyvhReOplqYoI_TNQHWukiYbxDjS_jAXcCC9epF_5zFiLDud1UzVusIF2zq4hlK0_wf-7lHqxB8MsEwdUuPka2Gmxv8pwVHy3sjnbo7BpAaPv27vzUcc1qjF-e9VpKd4W4Pgc', 'http://www.redcanina.es/playa-para-perros-es-carnatge-en-palma-de-mallorca/', NULL),

('Playa Canina de Llenaire', 'Pollença', 'Mallorca', 39.891648, 3.078516, 'Abierta todo el año. Sin retricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v6fntvF-QOY98Efa-wT0w1RqT2HzoDEXqUN-RSJ6twfyo6pJh1vSEheoXo5hFAQftG7pUKIM5Auwu7eVA1xVNoQ6mtnEdarS1_Wjsflvjwvf9Ox25AudmUPwPy43u5IHUJ8xKDGXIrqVlReXR8bBdzyHbYk7iAyLcztIqGOJ-ygVUDN_TkHbQ', 'http://www.redcanina.es/playa-para-perros-llenaire-en-pollenca/', NULL),

('Playa de na Patana', 'Calvià', 'Mallorca', 39.757663, 3.174759, 'Abierta todo el Año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v5SKJ-mwDpav3myPxozyXFBNnDHRnVngIerBmCSZVIwpmHBxGe73zdLfuVlGnUFNPSKiisK0eW3Z3OPwpTQff1BTtZuJIh7MjykPn_w0KHnYQT1z_bAtXLzzHY4Ybjqldq_a2s', 'http://www.redcanina.es/playa-de-na-patana-para-perros-en-mallorca/', NULL),

('Cala Blanca', 'Andratx', 'Mallorca', 39.536440, 2.405094, 'Abierta todo el año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v4isCDDmhJwI2DB8MNRYgNb3NFx89ZhEajoMhuiMW0hBYoepOidgdNXHs4hPGCT8oLfob2TgHZGfWRBxCWh-Ram86JXdT7mJi__UZ2EvpGZUas8UosZWDDTjLd6w-b-lZthJiU1Dnk', 'http://www.redcanina.es/cala-blanca-playa-para-perros-en-andratx/', NULL),

('Cala Gamba', 'Palma de Mallorca', 'Mallorca', 39.546385, 2.697916, 'Abierta todo el año. Sin Restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v7QyQa01sKBThdTOAdsVU_7KMpscxMUKC7PgIjQe8bTQnF1_Jjgbt3pMK6sF2q2llXfOq1FFyPlB0q9LdSeRN0gfK9aMNczVaPKNQa2zRBqOOybeBCMtWh7OG3nCYJ0c2fFMx7EPF-NWmOz8Z-AF_yDbGKz9AaSIRJIf8Fi3kLP1gqqXw', 'http://www.redcanina.es/cala-gamba-playa-para-perros-en-palma-de-mallorca/', NULL),

('Playa de Binigaus', 'Es Migjorn Gran', 'Menorca', 39.920688, 4.025288, 'Playa con restricción horaria en verano: Desde las 19h. hasta las 7 de la mañana', 'https://lh3.googleusercontent.com/umsh/AN6v0v7Cn6qI7XUbr6-5clVkUOGM9Muq6fjQgBrrOA83KLlshtfevcj8MPrxOEq0AQu3atl48f6O5uuR5rt1L0CNffuBbn3ADYfadmtHHIT01Bw_rhZT8-0CyqJs2LIsD8_Xnf9sUyhOzO5Byj0oaB_0', 'http://www.redcanina.es/cala-binigaus-para-perros-en-menorca-2/', NULL),

('Cala Escorxada', 'Es Migjorn Gran', 'Menorca', 39.925531, 4.004217, 'Abierta todo el año. Sin restricciones horarias', NULL, 'http://www.redcanina.es/cala-escorxada-para-perros-en-menorca/', NULL),

('Cala Fustam', 'Es Migjorn Gran', 'Menorca', 39.926081, 4.000971, 'Abierta todo el año. Sin restricciones horarias', 'https://lh3.googleusercontent.com/umsh/AN6v0v4KiDThQ9-XxNt5IUrkmtEs2AwJ2TwikfksiSQJOnIMbfDygg3kqVdDgXHUckGzVZQhmuCODQeMjUjs37gmYmB14V5SwKftZb4j_p_AqETBHzMbwxgAT2ibQKuWQo9t-chwxGB6bA', 'http://www.redcanina.es/cala-fustam-para-perros-en-menorca/', NULL),

('Playa Canina en Es Farralló', 'Santa Eulalia del Río', 'Ibiza', 38.987099, 1.545398, 'Abierta todo el año. Sin restricciones horarias.', 'https://lh3.googleusercontent.com/umsh/AN6v0v6l87ga_WJ4EDRt75waBDb0TZ1KOIrYMSv-GkvNAZdZE8bUXMwnCT537rUlvja4gUcjIU714IBD6bg53cGvALTceknjWKX0fft6IboYSUqqHgsK7pA6ymbOqRecOA7MIaCPJzw8k8mUST8UyhvyNOVoeMaXUl-sieW66bNWWDOwGEM3-UPxFtY', 'http://www.redcanina.es/playas-para-perros-en-santa-eulalia-del-rio-ibiza/', NULL),

('Playa Arroyo Totalán', 'Málaga', 'Málaga', 36.755814, -4.281540, 'Playa para perros en Málaga capital', 'https://lh3.googleusercontent.com/umsh/AN6v0v47jklS5VWFhIVk82VEkgTt05zTrdezYc__EG4UqNq3p1-oMMZEc3YbKJnR0Aq9yybQ_pe5Ux5cRQAu4dJl6wPKW6qYWDCY3KcKZHyO2i_i2GFhDdIDox3l5BLLiSKYBTuwhJ-VoIkU7k2yZY9MGOSMdzZrNjJ-CSo-GeuA08Ghp4-DYkAix-25SEfdxgOiYg', 'http://www.redcanina.es/playa-de-la-arana-para-perros-en-malaga/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-de-la-playa-arroyo-totalan-en-malaga/'),

('Playa del Castillo Sohail', 'Fuengirola', 'Málaga', 36.538208, -4.611896, 'Playa para perros en Fuengirola junto al Castillo Sohail', 'https://lh3.googleusercontent.com/umsh/AN6v0v5p5rkEV0YAoiJ3dDgHDHXGZCqDxZOzIRDj9JrjTxlRNzQv1x5F8GN9eQhVmYvGW0m_h41Z_TwmZQfzONYnRAztbvPXAe9TJJ8SJ1WTLOYg2SJcVwLtx3fUgdpUghkXv5-zMNbZ0T1vRQ', 'http://www.redcanina.es/playa-para-perros-en-fuengirola-malaga/', 'http://www.redcanina.es/alojamientos-que-admiten-perros-cerca-de-la-playa-canina-de-fuengirola/'),

('Playa de la Rana', 'Adra', 'Almería', 36.747929, -3.021244, 'Playa para perros en Adra, Almería', 'https://lh3.googleusercontent.com/umsh/AN6v0v4Gf0E_F8XLEjN4YQNxqNWIEojlO2_XDx8lYZ9k8DvmVEA3ORUj5yUGO3xY8kYUt_gPuWXb4E6VcDZiPnpGGvN3DYcwZJvLkwXLzL8JGjGGvP8VnxLX7xL', 'http://www.redcanina.es/playa-la-rana-para-perros-en-adra/', 'http://www.redcanina.es/alojamientos-que-admiten-mascotas-cerca-de-la-playa-de-la-rana/'),

('Cala Saliencia', 'Cudillero', 'Asturias', 43.561119, -6.162014, 'Playa para perros en Cudillero, Asturias', 'https://lh3.googleusercontent.com/umsh/AN6v0v5o2fEm_dF0yLkjV8YWNxCwP0ZKfZFXvGQqKNjx8GvP_gLXzL4YvLkXzL8JGjGGvN3DYcwZJvLkwXLzL8JGjGGvP8VnxLX7xL', 'https://www.playasparaperros.com/cala-saliencia-playa-perros-cudillero-asturias/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-cala-saliencia-novellana-cudillero/'),

('Playa de Llevant', 'Barcelona', 'Barcelona', 41.397564, 2.215826, 'Playa urbana para perros en Barcelona', 'https://lh3.googleusercontent.com/umsh/AN6v0v5LkQY_gN4ZcwP0VnxLX7xL8JGjGGvP8VnxLX7xL8JGjGGvN3DYcwZJvLkwXLzL8JGjGGvP8VnxLX7xL', 'https://www.playasparaperros.com/playa-de-llevant-playa-para-perros-en-barcelona/', 'https://www.playasparaperros.com/hoteles-apartamentos-admiten-perros-cerca-playa-llevant-barcelona/'),

('Playa de la Gola', 'Isla Cristina', 'Huelva', 37.195786, -7.318562, 'Playa para perros en Isla Cristina, Huelva', 'https://lh3.googleusercontent.com/umsh/AN6v0v47jklS5VWFhIVk82VEkgTt05zTrdezYc__EG4UqNq3p1-oMMZEc3YbKJnR0Aq9yybQ_pe5Ux5cRQAu4dJl6wPKW6qYWDCY3KcKZHyO2i_i2GFhDdIDox3l5BLLiSKYBTuwhJ-VoIkU7k2yZY9MGOSMdzZrNjJ-CSo-GeuA08Ghp4-DYkAix-25SEfdxgOiYg', NULL, NULL),

('Playa para perros en Estepona', 'Estepona', 'Málaga', 36.428201, -5.145862, 'Playa para perros en Estepona', NULL, 'https://www.redcanina.es/playa-para-perros-en-estepona-malaga/', NULL),

('Playa El Arenal', 'Jávea', 'Alicante', 38.791667, 0.175000, 'Playa para perros en Jávea, Alicante', NULL, 'https://www.redcanina.es/playa-para-perros-el-arenal-en-javea-alicante/', NULL);
